/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatBoard: typeof import('./components/chat/ChatBoard.vue')['default']
    ChatBubble: typeof import('./components/chat/ChatBubble.vue')['default']
    ChatComposer: typeof import('./components/chat/ChatComposer.vue')['default']
    GenSettingsBar: typeof import('./components/chat/GenSettingsBar.vue')['default']
    MemoryEditorDrawer: typeof import('./components/memory/MemoryEditorDrawer.vue')['default']
    ModelBar: typeof import('./components/chat/ModelBar.vue')['default']
    ModelCard: typeof import('./components/models/ModelCard.vue')['default']
    ModelsToolbar: typeof import('./components/models/ModelsToolbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreBreakdown: typeof import('./components/memory/ScoreBreakdown.vue')['default']
    ScoreExplainer: typeof import('./components/memory/ScoreExplainer.vue')['default']
    SessionSidebar: typeof import('./components/chat/SessionSidebar.vue')['default']
    SourceTrace: typeof import('./components/memory/SourceTrace.vue')['default']
    TraceTimeline: typeof import('./components/chat/TraceTimeline.vue')['default']
  }
}
